### ISSUE TITLE
Corregir presentación de título y descripción de videos de la página de tutoriales

### ISSUE THREAD

**Issue by gabvillacis** [Masappec/PNTv2#1]
Al entrar a la opción de tutoriales:

![Image](https://github.com/user-attachments/assets/1e035f1a-ec64-48e4-8bf1-2ddfa9a508c4)

... se despliega una lista de videos, esos videos ya están parametrizados desde el admin y ahí se les ha establecido un título y descripción sin embargo la página web de tutoriales no los está mostrando.

Se necesita que arriba de cada video salga su título y descripción que ya están parametrizados.

**Comment by ChaeMendoza** [comment]
### 🐛 Problema
En el archivo `TutorialsPresents.tsx`, el componente `<Iframe>` recibe el título (title) y la URL del video (url), pero no está recibiendo la descripción (description). Esto causa que la descripción del tutorial no se muestre en el componente final.

### 💡 Solución
Se actualizó el mapeo de los elementos en props.tutorial para incluir la descripción. Además, se añadieron mejoras visuales, como un `<hr />` antes y después de cada tutorial, junto con encabezados estilizados para el título y párrafos para la descripción.

### 🧩 Código antes
```
{
  props.tutorial.map((data) => {
    return (
      <>
        <Iframe title={data.title} link={formatUrlYoutube(data.url)} />
      </>
    );
  });
}

```
### 🔧 Código después
```
{
  props.tutorial.map((data) => {
    return (
      <>
        <hr />
        <h2 className="text-center text-2xl font-semibold text-gray">
          {data.title}
        </h2>
        <Iframe title={data.title} link={formatUrlYoutube(data.url)} />
        <p className="text-center text-gray-700 text-lg">
          {data.description}
        </p>
        <hr />
      </>
    );
  });
}
```
### 🚀 Cambios adicionales
- Se agregaron estilos de texto para mejorar la presentación del título y la descripción.
- Se añadió un `<hr />` para separar visualmente cada tutorial.
### 📸 Vista previa esperada
![issue](https://github.com/user-attachments/assets/4e2a8fcb-559a-4ac8-9aaa-a050f45c1763)
