### ISSUE TITLE
En el formulario de creación de instituciones (entidades) se debe eliminar el campo "Correo de acceso a la información"

### ISSUE THREAD

**Issue by gabvillacis** [Masappec/PNTv2#3]
En el formulario de creación de instituciones eliminar el campo "Correo de acceso a la información"

![Image](https://github.com/user-attachments/assets/583617c8-5a28-4568-a71e-4a7c73c29282)

![Image](https://github.com/user-attachments/assets/c675127c-561a-4727-b57c-037941341ca9)

En el back, para el llenado de la base de datos poner un email por defecto como "email@example.com" o dejarlo en nulo si es posible.
Validar que no se cause afectaciones en el sistema sobre el envío de correos de ese tipo.

**Comment by ChaeMendoza** [comment]
### Que se hizo?
Se eliminó el campo `Correo de acceso a la información` en la vista del formulario para cumplir con los requisitos de diseño. Además, se estableció un valor por defecto para este campo en el `frontend`, de modo que, al momento de crear o editar un registro, se asigne automáticamente.

### Modificaciones
`src/components/Admin/Establishment/Create`

```
const [data, setData] = useState<EstablishmentEntity>({
        abbreviation: "",
        code: "",
        email_authority: "",
        first_name_authority: "",
        highest_authority: "",
        last_name_authority: "",
        job_authority: "",
        logo: "",
        name: "",
        email_accesstoinformation: "email@example.com",
        email_committe: "",
        first_name_committe: "",
        highest_committe: "",
        job_committe: "",
        last_name_committe: "",
        identification: "",
        extra_numerals: '',
        address:""
    })
```

`src/components/Admin/Establishment/Edit`

```
const [data, setData] = useState<EstablishmentEntity>({
        abbreviation: "",
        code: "",
        email_authority: "",
        first_name_authority: "",
        highest_authority: "",
        last_name_authority: "",
        job_authority: "",
        logo: "",
        name: "",
        email_accesstoinformation: "email@example.com",
        email_committe: "",
        first_name_committe: "",
        highest_committe: "",
        job_committe: "",
        last_name_committe: "",
        identification: "",
        extra_numerals: '',
        address:""
    })
```


### Resultados
![Image](https://github.com/user-attachments/assets/edd626e8-be68-4865-85e3-95d654fd35e4)

![Image](https://github.com/user-attachments/assets/cca8b0fe-2cd4-458d-a7cf-3ac45261e960)
